In [4]:
# Set-up
import numpy as np
import scipy.linalg as sp

In [12]:
%%capture
%run forward-elimination.ipynb
%run backward-substitution.ipynb

In [13]:
def gauss_elim(A,b):
    U, z, Ms = forward_elim(A,b)
    back_subbed = back_sub(U,z)
    return back_subbed

In [14]:
print("########## GAUSSIAN ELIMINATION #########")
print("Testing Gaussian Elimination using the previous 2 functions:")
print("Input matrix: ")
for row in A1,b1:
    print(row)
print("Output solution: ")
i=1
print(gauss_elim(A1,b1)[0][0])

print("#########################################\n")

########## GAUSSIAN ELIMINATION #########
Testing Gaussian Elimination using the previous 2 functions:
Input matrix: 
[[ 1.  2.  2.]
 [ 0. -4. -6.]
 [ 0.  0. -1.]]
[[ 3.]
 [-6.]
 [ 1.]]
Output solution: 
-1.0
#########################################

