In [1]:
# Set-up
import numpy as np
import scipy.linalg as sp

In [2]:
%%capture
%run forward-elimination.ipynb
%run backward-substitution.ipynb

### LU factorization

In [3]:
def LU(A,b):
    U, z, Ms = forward_elim(A,b)
    L = np.identity(len(A))
    for Mi in Ms:
        L = L @ np.linalg.inv(Mi)
    return L, U, b

### Solver using $$Ax = LUx = b$$

In [5]:
def solve(A,b):
    L, U, b = LU(A,b)
    # LUx = b -> Ly = b
    _, y, _ = forward_elim(L,b)
    # Ux = y
    x = back_sub(U,y)
    return x

In [6]:
A1 = np.array([[1,2,2],[4,4,2],[4,6,4]])
b1 = np.array([[3],[6],[10]])

A2 = np.array([[1,3,-2],[1,5,3],[2,12,10]])
b2 = np.array([[1],[2],[3]])

A3 = np.array([[2,1,-1],[3,-1,2],[1,-1,-1]])
b3 = np.array([[5],[-1],[0]])

L1, U1, b = LU(A2,b2)
print("Result")
print(L1)
print(U1)

print(solve(A1,b1))
print(solve(A3,b3))

Result
[[1. 0. 0.]
 [1. 1. 0.]
 [2. 3. 1.]]
[[ 1.  3. -2.]
 [ 0.  2.  5.]
 [ 0.  0. -1.]]
[array([-1.]), array([3.]), array([-1.])]
[array([1.]), array([2.]), array([-1.])]
